name: Build LaTeX document
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: spec.tex
      - name: Upload documents
        uses: actions/upload-artifact@v3
        with:
          name: Telemetry Specifications
          path: Hybrid_Control_System_Packet_Format.pdf
      - name: Generate PDF page
        run: |
          mkdir pdfs
          cp Hybrid_Control_System_Packet_Format.pdf pdfs/
          cat > pdfs/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>File Browser</title>
            </head>
            <body>
            </body>
          </html>
          EOL
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: pdfs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
